/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemeRouteImport } from './routes/scheme'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as IndexRouteImport } from './routes/index'

const SchemeRoute = SchemeRouteImport.update({
  id: '/scheme',
  path: '/scheme',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/results': typeof ResultsRoute
  '/scheme': typeof SchemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/results': typeof ResultsRoute
  '/scheme': typeof SchemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/results': typeof ResultsRoute
  '/scheme': typeof SchemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details' | '/home' | '/language' | '/results' | '/scheme'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/home' | '/language' | '/results' | '/scheme'
  id:
    | '__root__'
    | '/'
    | '/details'
    | '/home'
    | '/language'
    | '/results'
    | '/scheme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  HomeRoute: typeof HomeRoute
  LanguageRoute: typeof LanguageRoute
  ResultsRoute: typeof ResultsRoute
  SchemeRoute: typeof SchemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheme': {
      id: '/scheme'
      path: '/scheme'
      fullPath: '/scheme'
      preLoaderRoute: typeof SchemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  HomeRoute: HomeRoute,
  LanguageRoute: LanguageRoute,
  ResultsRoute: ResultsRoute,
  SchemeRoute: SchemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
